services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ps\Contact\:
    resource: '../Classes/*'

  Ps\Contact\Command\ImportCommand:
    tags:
      - name: 'console.command'
        command: 'contact:import'